server:
  port: 8081
  servlet:
    context-path: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  tomcat:
    max-connections: 2000
  connection-timeout: 2000

spring:
  #  datasource:
  #    url: jdbc:postgresql://10.225.71.89:5432/nrise1
  #    username: nrise1
  #    password: nrise1
  #    driverClassName: org.postgresql.Driver
  #  jpa:
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        hbm2ddl: auto=update
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  global-config:
#    # 逻辑删除配置
#    db-config:
#      # 删除前
#      logic-not-delete-value: 1
#      # 删除后
#      logic-delete-value: 0
person:
  name: dengcong
  age: 28